### ISSUE TITLE
Send to the attic?

### ISSUE THREAD

**Issue by fofr** [alphagov/design-patterns#14]
This repo has been superseded by https://github.com/alphagov/govuk_elements/

I believe this repo can now be sent to the GDS Attic.

cc @gemmaleigh @timpaul

**Comment by timpaul** [comment]
:+1:

**Comment by stephenkeable** [comment]
Hi, I'm intrigued by the lack of a page for Address forms on the new elements manual.

Is there now an alternative page anywhere? As at Allies Computing we refer some of our customers to the addresses page for examples of how to structure address forms.

**Comment by timpaul** [comment]
Hi Stephen. We discuss various approaches to capturing addresses in the [design patterns section of the service manual](https://www.gov.uk/service-manual/user-centred-design/resources/patterns/addresses.html)

**Comment by stephenkeable** [comment]
@timpaul That's great thanks for the response.

**Comment by tijmenb** [comment]
I'll archive this repo.
